server:
  port: 8084

management:
  port: 8085
  security.enabled: true


spring:
  application:
    name: adminserver


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://microservice:pwd@localhost:8082/eureka/
