server:
  port: 8082

management:
  port: 8083
  security.enabled: false

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true # so the Admin Server can discover eureka
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
