server:
  port: 8082

management:
  security.enabled: true
  info:
    git:
      mode: simple
  context-path: /actuator


spring:
  application:
    name: eureka

eureka:
  server:
      waitTimeInMsWhenSyncEmpty: 0

  instance:
    hostname: localhost
    metadata-map: # so the Admin Server can get the login / password and connect
      user.name: microservice
      user.password: pwd
      management.context-path: ${management.context-path}

  client:
    registerWithEureka: true # so the Admin Server can discover eureka
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://microservice:${security.user.password}@localhost:8082/eureka/


security:
  basic:
    enabled: true
  user:
      name: microservice
      password: pwd
