server:
  port: 8082

management:
  port: 8083
  security.enabled: false

spring:
  application:
    name: eureka

eureka:
  server:
      waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost

  client:
    registerWithEureka: true # so the Admin Server can discover eureka
#    initial-instance-info-replication-interval-seconds: 10 # wait to be sure that the server is started
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://microservice:pwd@localhost:8082/eureka/

security:
  basic:
    enabled: true
  user:
      name: microservice
      password: pwd
